### PR TITLE
Make the algorithm more robust

### LINKED ISSUE #20: Can't handle bcrypt password structure
Hi,

I've encountered with a weird bug, I've a bcrypt pass that looks like that `$2b$10$OMZ69gxxsmRgwAt945WHSujpr/u8ZMx.xwtxWOCMkeMW7p3XqKYca` (it is not a real pass 😁), I've escaped the `$` sign `\$2b\$10\$OMZ69gxxsmRgwAt945WHSujpr/u8ZMx.xwtxWOCMkeMW7p3XqKYca` it falls to the [first condition](https://github.com/motdotla/dotenv-expand/blob/master/lib/main.js#L25), and therefore it returns `$2b\$10\$OMZ69gxxsmRgwAt945WHSujpr/u8ZMx.xwtxWOCMkeMW7p3XqKYca` that is wrong.

I don't think that it is a good solution to escape only the first `$`, which will work till it won't.

So, I will make a PR for more robust solution.

### PR DESCRIPTION
**Pull request by felixmosh**
This PR fixes #20

A short explanation of the algorithm: 
1. extract all the $params with the prefix char of the `$` sign
2. break each one of the individual match to parts that will contain the $ prefix char, key.
3. condition, if the prefix is escape char, replace the escape char to nothing, 
    else, replace recursively like before.

### CODE REVIEW

**Comment by felixmosh** [comment]
@motdotla can you review?

**Comment by ericrallen** [comment]
I ran this PR through some tests, and it seems to be working as expected.

Though, the issue does make me wonder if deprecating the "basic" expansion would be a good idea.

Explicitly marking something as a variable you want expanded with the `${VAR}` syntax seems like the more logical and robust approach.

File: lib/main.js [hunk 1]
```diff
@@ -1,34 +1,36 @@
...
     var value = process.env.hasOwnProperty(configKey) ? process.env[configKey] : config.parsed[configKey]
 
-    if (config.parsed[configKey].substring(0, 2) === '\\$') {
-      config.parsed[configKey] = value.substring(1)
-    } else if (config.parsed[configKey].indexOf('\\$') > 0) {
-      config.parsed[configKey] = value.replace(/\\\$/g, '$')
-    } else {
-      config.parsed[configKey] = interpolate(value)
-    }
+    config.parsed[configKey] = interpolate(value)
```
Comment (ericrallen) [inline lib/main.js]: It's nice how this simplifies the logic here to a single method method call.

File: lib/main.js [hunk 2]
```diff
@@ -1,34 +1,36 @@
...
-      env = env.replace(match, variable)
-    })
-
-    return env
+  var interpolate = function (envValue) {
+    var matches = envValue.match(/(.?\${?(?:[a-zA-Z0-9_]+)?}?)/g) || []
+
+    return matches.reduce(function (newEnv, match) {
+      var parts = /(.?)\${?([a-zA-Z0-9_]+)?}?/g.exec(match)
+      var $prefix = parts[1]
```
Comment (ericrallen) [inline lib/main.js]: Would this just be better as `prefix` instead of prefixing it with a `$`, too?

File: test/main.js [hunk 3]
```diff
@@ -112,6 +112,31 @@ describe('dotenv-expand', function () {
       obj['SOME_ENV'].should.eql('production')
       done()
     })
+
+    it('does not expand inline escaped dollar sign', function (done) {
+      var dotenv = {
+        parsed: {
+          'INLINE_ESCAPED_EXPAND_BCRYPT': '\\$this\\$is\\$bcrypt'
```
Comment (ericrallen) [inline test/main.js]: Should we go ahead and add the test case you brought up in #20? That way it's easy to make sure that any future changes don't break the handling of a real bcrypt string?

File: test/main.js [hunk 4]
```diff
@@ -112,6 +112,31 @@ describe('dotenv-expand', function () {
...
+
+      obj['INLINE_ESCAPED_EXPAND_BCRYPT'].should.eql('$this$is$bcrypt')
+      done()
+    })
+
+    it('handle mixed values', function (done) {
+      var dotenv = {
+        parsed: {
+          'PARAM1': '42',
+          'MIXED_VALUES': '\\$this$PARAM1\\$is${PARAM1}'
```
Comment (ericrallen) [inline test/main.js]: Glad to see a test that mixes not only the escaped and unescaped, but also the basic and the `${VAR}` expanded syntax.

**Comment by felixmosh** [comment]
> I ran this PR through some tests, and it seems to be working as expected.
> 
> Though, the issue does make me wonder if deprecating the "basic" expansion would be a good idea.
> 
> Explicitly marking something as a variable you want expanded with the `${VAR}` syntax seems like the more logical and robust approach.

I do think that it is better to strict the expention to ${} would be better, just wanted not to break past support :)

File: lib/main.js (hunk 1 above)
Comment (felixmosh) [reply lib/main.js]: 👍

File: lib/main.js (hunk 2 above)
Comment (felixmosh) [reply lib/main.js]: It is the prefix of the $ sign :), but I can change it if you insist

File: test/main.js (hunk 3 above)
Comment (felixmosh) [reply test/main.js]: Will do

File: test/main.js (hunk 4 above)
Comment (felixmosh) [reply test/main.js]: 👍

File: lib/main.js [hunk 5]
```diff
@@ -1,34 +1,36 @@
...
-      env = env.replace(match, variable)
-    })
-
-    return env
+  var interpolate = function (envValue) {
+    var matches = envValue.match(/(.?\${?(?:[a-zA-Z0-9_]+)?}?)/g) || []
+
+    return matches.reduce(function (newEnv, match) {
+      var parts = /(.?)\${?([a-zA-Z0-9_]+)?}?/g.exec(match)
+      var prefix = parts[1]
```
Comment (ericrallen) [inline lib/main.js]: What about something like this?

```
var isPrefixed = parts[1] === '\\';

if (isPrefixed) {
  //...
```

Comment (felixmosh) [reply lib/main.js]: Actually I've put some thought into it before submitting the PR, I think that this way it is more explicit.

Comment (ericrallen) [reply lib/main.js]: Technically this doesn't really matter, but I wanted to share my thought process. Full disclosure: I'm just a person on the Internet with opinions.

I could see a valid argument that the `prefix` variable itself isn't actually important or useful in any way and the only thing we actually care about is if it matches the `\` character, and that the explicitness actually makes what is important less clear in this case.

Also, out of curiosity, is the `\` technically more of an escape than a prefix in this case? Should the name better reflect what this character represents? Like should it be `escpae` (and `isEscaped` in the case of my example)?

Comment (felixmosh) [reply lib/main.js]: No problem, I like your comment.
In this case I don’t agree, because ‘parts[1]’ is the prefix char of $ sign. It may contain any chars event the empty one.
Therefore the name.

I can refactor the condition into an additional variable name isEsacped, WDYT?

Comment (ericrallen) [reply lib/main.js]: That just adds an extra variable.

I still think the `prefix` variable is extraneous, but it's not a big deal.

**Comment by ericrallen** [comment]
@felixmosh Hey there, I just merged in the other open PR that had been waiting for quite a long time.

If you could rebase your branch we can go ahead and get this merged in, too.

Thanks for the contribution!

**Comment by felixmosh** [comment]
@ericrallen version 5.1.0 is not released yet, when will it be released?

**Comment by motdotla** [comment]
Give it a try now. Just released.
